### PR TITLE
Add Lang Portuguese pt-BR

### PR DESCRIPTION
**Pull request by maisondasilva**
Add Lang Portuguese pt-BR

### CODE REVIEW

**Comment by maisondasilva** [comment]
@jakobbouchard @jakobbouchard Is this useful?

**Comment by jaapmarcus** [comment]
There is some hard coded text written that won't be translated.. 

https://github.com/jakobbouchard/hestia-nginx-cache/blob/7400f9395472ac022b604ae0e31e21a865482028/assets/js/admin.js#L17

**Comment by jaapmarcus** [comment]
Also I don't think .pot files work it should be .po?

**Comment by jaapmarcus** [comment]
https://www.quora.com/What-is-the-difference-between-po-mo-and-pot-files-in-WordPress-localization#:~:text=In%20summary%2C%20the%20.,translated%20strings%20on%20the%20website.

It needs to be .mo + .po

**Comment by maisondasilva** [comment]
@jaapmarcus In fact, I only added the translation as a contribution, but I also believe it should be .po

**Comment by imjuniper** [comment]
I obviously cannot verify the translations, but thanks for the PR, I'll merge this:) I'll try to add the localized text in the JavaScript using the WP functions for it soon, but I am very busy with university right now.

**Pull request merged**
