### PR TITLE
fix value & disable ssl verify and increase timeout

### PR DESCRIPTION
**Pull request by TriggerLab**

### CODE REVIEW

**Comment by imjuniper** [comment]
Thanks for the PR! Just wondering though, don't all Hestia installations have SSL enabled? So SSL verification shouldn't cause problems? @jaapmarcus can you confirm this?

**Comment by TriggerLab** [comment]
> Thanks for the PR! Just wondering though, don't all Hestia installations have SSL enabled? So SSL verification shouldn't cause problems? @jaapmarcus can you confirm this?

This disables self-signed cert verification, i tested it and everything works fine.

**Comment by jaapmarcus** [comment]
If you use https://ip:8083 or run behind proxy ssl might be a self singed one and they don't work on default

**Comment by imjuniper** [comment]
Oooh yeah right that makes sense!

**Pull request merged**
