### PR TITLE
Feature Disable Auto Purge

### PR DESCRIPTION
**Pull request by jaapmarcus**
See: https://forum.hestiacp.com/t/apache2-and-nginx-restart-every-few-minutes/13628/3

### CODE REVIEW

**Comment by jaapmarcus** [comment]
.pot / translations has not been updated

**Comment by imjuniper** [comment]
i'll update the translation and merge a little later this week

**Comment by bojandenic** [comment]
> i'll update the translation and merge a little later this week

Any news? Thanks!

**Comment by imjuniper** [comment]
Sorry for the late reply. I'll be doing this today, things got quite busy at work!

**Pull request merged**
