### PR TITLE
Update pt-BR for new version

### PR DESCRIPTION
**Pull request by maisondasilva**
Update pt-BR for new version

### CODE REVIEW

**Comment by maisondasilva** [comment]
@jakobbouchard

**Comment by imjuniper** [comment]
The msgid should stay in english, since that's the string it searches for:)

**Comment by maisondasilva** [comment]
Yes, send the wrong file, I was seeing this now, I will correct it and send it again!

**Comment by maisondasilva** [comment]
Corrected, I just don't understand why this line ended up like that! @jakobbouchard 

`#: includes/admin.php:106
msgid ""
"Please refer to the plugin's installation guide for information on how to "
"generate an API key."
msgstr ""
"Por favor, consulte o guia de instalação do plugin para obter informações "
"sobre como gerar uma chave de API."`

**Comment by maisondasilva** [comment]
Fix @jakobbouchard

**Pull request closed without merging**
